
dotfiles_dir = ".config/nat-config"


[settings.dots]

i3status = { source = "i3status", target = ".config/i3status" }
sway = { source = "sway", target = ".config/sway" }
nvim = { source = "nvim", target = ".config/nvim" }
konsole = { source = "konsole", target = "~/.local/share/konsole" }
konsolerc = { source = "konsole/konsolerc", target = ".config/konsolerc" }
gnvim = { source = "bin/gnvim", target = "~/.local/bin/gnvim" }
vc = { source = "bin/vc", target = "~/.local/bin/vc" }
